#Make sure that we have sudo permission before doing some operations
sudo: required
language: generic

#Docker CLI installed
services:
  - docker
  
#Series of command needed before our tests command
before_install:
  - docker build -t ostin/docker-react -f Dockerfile.dev .

#Describing the commands used to execute test suite
script:
  - docker run -e CI=true ostin/docker-react npm run test
  
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-1-776373242308"
#   bucket_path: "docker-react"
#   on:
#     branch : master